import { createApp } from 'vue'
import App from './App.vue'
import './styles.css'
import './header.css'
import './highlights-hero.css'
import './about.css'
import './team-robots-awards.css'
import './gallery.css'
import './events.css'
createApp(App).mount('#app')
