import { createApp } from 'vue'
import App from './App.vue'
import './styles.css'
import './header.css'
import './header-identity.css'
import './highlights-hero.css'
import './about.css'
import './team-robots-awards.css'
import './gallery.css'
import './gallery-external.css'
import './events.css'
import './active-competition.css'
import './footer.css'
import './footer-ruby.css'
import './not-found.css'
createApp(App).mount('#app')
